package:
  name: aws-c-mqtt
  version: 0.8.7
  epoch: 0
  description: AWS C99 implementation of the MQTT 3.1.1 specification
  copyright:
    - license: Apache-2.0
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
      - '@local ./packages'
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - cmake
      - samurai
      - aws-c-cal-dev@local
      - aws-c-common-dev@local
      - aws-c-compression-dev@local
      - aws-c-http-dev@local
      - aws-c-io-dev@local
      - openssl-dev
      - s2n-tls-dev@local
pipeline:
  - uses: fetch
    with:
      expected-sha512: 7abf065b4c2a2e6552d89a40efb98db90540a9ae6bf1bf893f7701c10512de0117f0be557b98d2cd226ae56bf8b59c36fb4411bb98e58fec1fb7057775d9596d
      uri: https://github.com/awslabs/aws-c-mqtt/archive/refs/tags/v${{package.version}}.tar.gz
  - runs: |
      if [ "$CBUILD" != "$CHOST" ]; then
        CMAKE_CROSSOPTS="-DCMAKE_SYSTEM_NAME=Linux -DCMAKE_HOST_SYSTEM_NAME=Linux"
      fi
      CFLAGS="$CFLAGS -flto=auto" \
      CXXFLAGS="$CXXFLAGS -flto=auto" \
      cmake -B build -G Ninja \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=/usr/lib \
        -DBUILD_SHARED_LIBS=True \
        -DCMAKE_BUILD_TYPE=None \
        -DBUILD_TESTING="$(want_check && echo ON || echo OFF)" \
        $CMAKE_CROSSOPTS
      cmake --build build
  - runs: |
      DESTDIR="${{targets.destdir}}" cmake --install build      
  - uses: strip
subpackages:
  - name: aws-c-mqtt-dev
    pipeline:
      - uses: split/dev
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/aws-c-mqtt "${{targets.subpkgdir}}"/usr/lib/
    dependencies:
      runtime:
        - aws-c-mqtt
    description: aws-c-mqtt dev
