package:
  name: aws-crt-cpp
  version: 0.19.8
  epoch: 0
  description: "C++ wrapper around the aws-c-* libraries. Provides Cross-Platform Transport Protocols and SSL/TLS implementations for C++"
  copyright:
    - license: Apache-2.0
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
      - '@local ./packages'
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - cmake
      - samurai
      - aws-c-auth-dev@local
      - aws-c-cal-dev@local
      - aws-c-common-dev@local
      - aws-c-compression-dev@local
      - aws-c-event-stream-dev@local
      - aws-c-http-dev@local
      - aws-c-io-dev@local
      - aws-c-mqtt-dev@local
      - aws-c-s3-dev@local
      - aws-c-sdkutils-dev@local
      - aws-checksums-dev@local
      - s2n-tls-dev@local
      - git
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/awslabs/aws-crt-cpp
      tag: v${{package.version}}
      expected-commit: d9ca0e08505d96116b1018f7e2fd60a2e06a01e3
      destination: aws-crt-cpp
  - runs: |
      cd aws-crt-cpp
      git submodule update --init
  - runs: |
      cd aws-crt-cpp
      if [ "$CBUILD" != "$CHOST" ]; then
        CMAKE_CROSSOPTS="-DCMAKE_SYSTEM_NAME=Linux -DCMAKE_HOST_SYSTEM_NAME=Linux"
      fi
      CFLAGS="$CFLAGS -flto=auto" \
      CXXFLAGS="$CXXFLAGS -flto=auto" \
      cmake -B build -G Ninja\
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=/usr/lib \
        -DBUILD_SHARED_LIBS=True \
        -DCMAKE_BUILD_TYPE=None \
        -DBUILD_DEPS=False \
        -DBUILD_TESTING="$(want_check && echo ON || echo OFF)" \
        $CMAKE_CROSSOPTS
      cmake --build build
  - runs: |
      cd aws-crt-cpp
      DESTDIR="${{targets.destdir}}" cmake --install build
      rm -rf "${{targets.destdir}}"/usr/bin/
  - uses: strip
subpackages:
  - name: aws-crt-cpp-dev
    pipeline:
      - uses: split/dev
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/aws-crt-cpp "${{targets.subpkgdir}}"/usr/lib/
    dependencies:
      runtime:
        - aws-c-auth-dev
        - aws-c-cal-dev
        - aws-c-common-dev
        - aws-c-compression-dev
        - aws-c-event-stream-dev
        - aws-c-http-dev
        - aws-c-io-dev
        - aws-c-mqtt-dev
        - aws-c-s3-dev
        - aws-c-sdkutils-dev
        - aws-checksums-dev
        - aws-crt-cpp
        - s2n-tls-dev
    description: aws-crt-cpp dev