package:
  name: aws-c-io
  version: 0.13.19
  epoch: 0
  description: Module for the AWS SDK for C handling all IO and TLS work for application protocols
  copyright:
    - license: Apache-2.0
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
      - '@local ./packages'
    packages:
      - aws-c-cal-dev@local
      - aws-c-common-dev@local
      - busybox
      - build-base
      - ca-certificates-bundle
      - cmake
      - s2n-tls-dev@local
      - openssl-dev
      - samurai
pipeline:
  - uses: fetch
    with:
      expected-sha512: a0209a6420a8c464508a7e51504e7e07f0155018b2b9201a6b6016a317a33e18c2103ae3f7a0c0a0959273505f617e8f763d51dc57c807a0785cf5fbeedc69bc
      uri: https://github.com/awslabs/aws-c-io/archive/refs/tags/v${{package.version}}.tar.gz
  - runs: |
      if [ "$CBUILD" != "$CHOST" ]; then
        CMAKE_CROSSOPTS="-DCMAKE_SYSTEM_NAME=Linux -DCMAKE_HOST_SYSTEM_NAME=Linux"
      fi
      CFLAGS="$CFLAGS -flto=auto" \
      CXXFLAGS="$CXXFLAGS -flto=auto" \
      cmake -B build -G Ninja \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=/usr/lib \
        -DBUILD_SHARED_LIBS=True \
        -DCMAKE_BUILD_TYPE=None \
        -DBUILD_TESTING="$(want_check && echo ON || echo OFF)" \
        -DUNSAFE_TREAT_WARNINGS_AS_ERRORS=OFF \
        $CMAKE_CROSSOPTS
      cmake --build build
  - runs: |
      DESTDIR="${{targets.destdir}}" cmake --install build
  - uses: strip
subpackages:
  - name: aws-c-io-dev
    pipeline:
      - uses: split/dev
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/aws-c-io "${{targets.subpkgdir}}"/usr/lib/
    dependencies:
      runtime:
        - openssl-dev
        - aws-c-io
    description: aws-c-io dev
