package:
  name: aws-c-common
  version: 0.8.14
  epoch: 0
  description: Core c99 package for AWS SDK for C including cross-platform primitives, configuration, data structures, and error handling
  copyright:
    - license: Apache-2.0
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - cmake
      - samurai
      - cmake
      - python3-dev
pipeline:
  - uses: fetch
    with:
      expected-sha512: 221ff2d8e058ca1586c41d9b4e807c75fe2ef824112bca25428b327f35018a61f9d6f152a730f0214c85afcb604de58a928f19f9b78edb106414ef176bd6dcdd
      uri: https://github.com/awslabs/aws-c-common/archive/refs/tags/v${{package.version}}.tar.gz
  - runs: |
      if [ "$CBUILD" != "$CHOST" ]; then
        CMAKE_CROSSOPTS="-DCMAKE_SYSTEM_NAME=Linux -DCMAKE_HOST_SYSTEM_NAME=Linux"
      fi
      CFLAGS="$CFLAGS -flto=auto" \
      CXXFLAGS="$CXXFLAGS -flto=auto" \
      cmake -B build -G Ninja \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DBUILD_SHARED_LIBS=True \
        -DCMAKE_BUILD_TYPE=None \
        -DBUILD_TESTING="$(want_check && echo ON || echo OFF)" \
        $CMAKE_CROSSOPTS
      cmake --build build
  - runs: |
      DESTDIR="${{targets.destdir}}" cmake --install build
  - uses: strip
subpackages:
  - name: aws-c-common-dev
    pipeline:
      - uses: split/dev
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/aws-c-common "${{targets.subpkgdir}}"/usr/lib/
    description: aws-c-common dev
