package:
  name: aws-c-s3
  version: 0.2.6
  epoch: 0
  description: "AWS C99 library implementation for communicating with the S3 service"
  copyright:
    - license: Apache-2.0
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
      - '@local ./packages'
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - samurai
      - aws-c-auth-dev@local
      - aws-c-cal-dev@local
      - aws-c-common-dev@local
      - aws-c-compression-dev@local
      - aws-c-http-dev@local
      - aws-c-io-dev@local
      - aws-c-sdkutils-dev@local
      - aws-checksums-dev@local
      - curl-dev
      - s2n-tls-dev@local
pipeline:
  - uses: fetch
    with:
      expected-sha512: cbd99103653d95f52d463d2000ebd9c46729ab6df29f8a77a082f7009e71e4c21e0342f945dc9282a92b03136e8830269c4c663f8b2987a4f7677fd9a8d523d7
      uri: https://github.com/awslabs/aws-c-s3/archive/refs/tags/v${{package.version}}.tar.gz
  - runs: |
      if [ "$CBUILD" != "$CHOST" ]; then
        CMAKE_CROSSOPTS="-DCMAKE_SYSTEM_NAME=Linux -DCMAKE_HOST_SYSTEM_NAME=Linux"
      fi
      CFLAGS="$CFLAGS -flto=auto" \
      CXXFLAGS="$CXXFLAGS -flto=auto" \
      cmake -B build -G Ninja \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=/usr/lib \
        -DBUILD_SHARED_LIBS=True \
        -DCMAKE_BUILD_TYPE=None \
        -DBUILD_TESTING="$(want_check && echo ON || echo OFF)" \
        $CMAKE_CROSSOPTS
      cmake --build build
  - runs: |
      DESTDIR="${{targets.destdir}}" cmake --install build
  - uses: strip
subpackages:
  - name: aws-c-s3-dev
    pipeline:
      - uses: split/dev
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/aws-c-s3 "${{targets.subpkgdir}}"/usr/lib/
    dependencies:
      runtime:
        - aws-c-s3
    description: aws-c-s3 dev
