package:
  name: py3-wcwidth
  version: 0.2.6
  epoch: 0
  description: Measures number of Terminal column cells of wide-character codes
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/w/wcwidth/wcwidth-${{package.version}}.tar.gz
      expected-sha512: 0f7be2fcf0a2ef1c357fb3d1f7041a309443c8c771973aaf3acb7d83acee9fababa7f17dabc886a37d20bfc7dc13e8b0ce18637f4137ab349c881697e18c3a1c
  - runs: |
      python3 setup.py build
      python3 setup.py install --skip-build --root="${{targets.destdir}}"
      rm -f "${{targets.destdir}}"/usr/lib/python3*/site-packages/certifi/cacert.pem
  - uses: strip
