package:
  name: py3-altgraph
  version: 0.17.3
  epoch: 0
  description: Python graph (network) package
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/a/altgraph/altgraph-${{package.version}}.tar.gz
      expected-sha256: ad33358114df7c9416cdb8fa1eaa5852166c505118717021c6a8c7c7abbd03dd
  - runs: |
      python3 setup.py build
      python3 setup.py install --skip-build --root="${{targets.destdir}}"
  - uses: strip
