package:
  name: py3-distro
  # distro (required: ('>=1.5.0', '<1.6.0')) (version installed: 1.8.0)
  version: 1.5.0
  epoch: 0
  description: A Linux OS platform information API
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - python3

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-gpep517
      - py3-installer
      - py3-setuptools
      - py3-pip
      - python3
      - python3-dev
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/d/distro/distro-${{package.version}}.tar.gz
      expected-sha256: 0e58756ae38fbd8fc3020d54badb8eae17c5b9dcbed388b17bb55b8a5928df92
  - runs: |
      python3 -m pip install --disable-pip-version-check -U pip
      python3 -m pip install -U build twine
      python3 -m build
      python3 -m installer -d "${{targets.destdir}}" dist/*.whl
  - uses: strip
