package:
  name: py3-ruamel.yaml
  version: 0.17.21
  epoch: 0
  description: A YAML parser/emitter
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3
      # - py3-ruamel.yaml.clib

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - python3-dev
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/r/ruamel.yaml/ruamel.yaml-${{package.version}}.tar.gz
      expected-sha512: 1ecda5ecacf913a499e40b4df8d5d6112b8c2facf5ce42c36eedad1ea4745884f98919b70a9d51ba8b095463e27371f6b84e314fe8f512c318963ab32f2cbf17
  - runs: |
      python3 setup.py build
      RUAMEL_NO_PIP_INSTALL_CHECK=1 python3 setup.py install --skip-build --root="${{targets.destdir}}"
  - uses: strip
