package:
  name: py3-pyinstaller
  version: 5.8.0
  epoch: 0
  description: Freeze (package) Python programs into stand-alone executables 
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
      - ./packages
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - python3-dev
      - wolfi-base
      - py3-wheel@local
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/p/pyinstaller/pyinstaller-${{package.version}}.tar.gz
      expected-sha256: 314fb883caf3cbf06adbea2b77671bb73c3481568e994af0467ea7e47eb64755
  - runs: |
      python3 setup.py build
      python3 setup.py install --skip-build --root="${{targets.destdir}}"
  - uses: strip
