package:
  name: py3-awscrt
  version: 0.16.12
  epoch: 0
  description: Python bindings for the AWS Common Runtime
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - python3

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
      - '@local ./packages'
    packages:
      - aws-crt-cpp-dev@local
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-gpep517
      - py3-installer
      - py3-setuptools
      - python3
      - python3-dev
      - wolfi-base
      - samurai

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/awslabs/aws-crt-python/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha512: 0309d75cd7e5fe423d6066656676b38652f54d6d96707901b87c6a6d6faa20f204a99b810cd765f9cc940eb5ace0400aeb1b95f8b192b4125b2d2c167656a00e
  - runs: |
      echo "__version__ = '${{package.version}}'" >> awscrt/__init__.py
      sed -i '/:lib/d' setup.py
      python3 setup.py build
      python3 setup.py install --skip-build --root="${{targets.destdir}}"
  - uses: strip
