package:
  name: py3-cryptography
  version: 39.0.2
  epoch: 0
  description: Cryptographic recipes and primitives for Python
  copyright:
    - license: Apache-2.0 OR BSD-3-Clause
  dependencies:
    runtime:
      - python3
      - py3-cffi

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
      - '@local ./packages'
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - python3-dev
      - wolfi-base
      - libffi-dev
      - openssl-dev
      - py3-setuptools-rust@local

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/c/cryptography/cryptography-${{package.version}}.tar.gz
      expected-sha512: 10184814f262f2d5f505abf4dcb73eb0de59aadca2e228b2bacf6e03eb124efdc9504e752976fcb58f2ee673dc84230180873c28b85cd18e1831ab3c44022c01
  - runs: |
      python3 setup.py build
      python3 setup.py install --skip-build --root="${{targets.destdir}}"
  - uses: strip
