package:
  name: py3-cffi
  version: 1.15.1
  epoch: 0
  description: Foreign function interface for calling C code from Python3
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3
      - py3-cparser

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - python3-dev
      - wolfi-base
      - libffi-dev

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/c/cffi/cffi-${{package.version}}.tar.gz
      expected-sha512: e99cafcb029076abc29e435b490fa0573ee2856f4051b7ca8a5b38cd125d56dd9dae8b189f59ceb3d728a675da8ee83239e09e19f8b0feeddea4b186ab5173a5
  - runs: |
      python3 setup.py build
      python3 setup.py install --skip-build --root="${{targets.destdir}}"
  - uses: strip
