package:
  name: py3-distro
  version: 1.8.0
  epoch: 0
  description: A Linux OS platform information API
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - python3

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-gpep517
      - py3-installer
      - py3-setuptools
      - py3-pip
      - python3
      - python3-dev
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/d/distro/distro-${{package.version}}.tar.gz
      expected-sha512: 027fe8bc50e263dc49451932774f32cea7900820b6e30cc80afcdc84374777ba733137fdd8d27fec76f66ce9c579bc172721e7ae0f43e72dffbc092126b26af2
  - runs: |
      python3 -m pip install --disable-pip-version-check -U pip
      python3 -m pip install -U build twine
      python3 -m build
      python3 -m installer -d "${{targets.destdir}}" dist/*.whl
  - uses: strip
